import {test,expect} from '@playwright/test';
test('ник, список игр, смена ника, матч, очередь, закрытие и восстановление',async({browser})=>{
  const a=await browser.newContext({viewport:{width:1440,height:900}}),b=await browser.newContext({viewport:{width:1440,height:900}});const page=await a.newPage(),friend=await b.newPage(),errors=[];let latest;
  page.on('pageerror',e=>errors.push(e.message));friend.on('pageerror',e=>errors.push(e.message));page.on('websocket',ws=>ws.on('framereceived',frame=>{try{const m=JSON.parse(frame.payload);if(m.state)latest=m.state;}catch{}}));
  try{
    await page.goto('/');await expect(page.getByRole('heading',{name:'Как вас называть?'})).toBeVisible();await page.getByLabel('ПОЗЫВНОЙ',{exact:true}).fill('Commander');await page.getByRole('button',{name:'Войти в штаб'}).click();await expect(page.getByRole('heading',{name:'Найди свой бой.'})).toBeVisible();await page.screenshot({path:'test-results/browser-desktop.png'});
    await page.getByTitle('Изменить позывной').click();await page.getByLabel('ПОЗЫВНОЙ',{exact:true}).fill('Before');await page.getByRole('button',{name:'Войти в штаб'}).click();await expect(page.locator('#nickname')).toHaveText('Before');
    await page.getByRole('button',{name:'＋ Создать игру'}).click();await page.getByLabel('НАЗВАНИЕ КОМНАТЫ').fill('Desert friends');await page.getByRole('button',{name:'Создать комнату',exact:true}).click();await expect(page.locator('#room')).toBeVisible();await page.getByTitle('Изменить позывной').click();await page.getByRole('dialog').getByLabel('ПОЗЫВНОЙ',{exact:true}).fill('Alpha');await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.locator('#dialog')).not.toBeVisible();await expect(page.locator('#nickname')).toHaveText('Alpha');
    await friend.goto('/');await friend.getByLabel('ПОЗЫВНОЙ',{exact:true}).fill('Bravo');await friend.getByRole('button',{name:'Войти в штаб'}).click();const row=friend.locator('.room-row').filter({hasText:'Desert friends'});await expect(row).toBeVisible();await row.getByRole('button',{name:'Подключиться',exact:true}).click();await expect(friend.locator('#room')).toBeVisible();await page.getByRole('button',{name:'Я готов',exact:true}).click();await friend.getByRole('button',{name:'Я готов',exact:true}).click();await page.getByRole('button',{name:'Начать матч →'}).click();await expect(page.locator('#ui')).toBeVisible();await expect(friend.locator('#ui')).toBeVisible();await expect.poll(()=>latest?.units?.length).toBe(12);
    const oldId=latest.players.find(p=>p.name==='Alpha').id,oldUnit=latest.units.find(u=>u.owner===oldId);await page.keyboard.press('Shift+1');await expect(page.locator('#group-1')).toContainText('6');
    await page.locator('[data-unit=tank]').click();await expect(page.locator('#queue-items button')).toHaveCount(1);await page.locator('#queue-items button').click();await expect(page.locator('#queue-items button')).toHaveCount(0);await page.locator('[data-unit=scout]').click();await expect(page.locator('#population')).toHaveText('7',{timeout:10000});
    const mm=await page.locator('#minimap').boundingBox();await page.mouse.click(mm.x+mm.width*.5,mm.y+mm.height*.5,{button:'right'});await expect.poll(()=>latest.units.find(u=>u.id===oldUnit.id)?.x).not.toBe(oldUnit.x);await page.screenshot({path:'test-results/battle-desktop.png'});
    let protection=false;page.once('dialog',async d=>{protection=d.type()==='beforeunload';await d.dismiss();});await page.reload({timeout:7000}).catch(()=>{});expect(protection).toBe(true);await expect(page.locator('#ui')).toBeVisible();
    page.once('dialog',d=>d.accept());await page.reload();await expect(page.locator('#ui')).toBeVisible({timeout:12000});await expect.poll(()=>latest.players.find(p=>p.name==='Alpha')?.id).toBe(oldId);await expect(page.locator('#population')).toHaveText('7');
    await page.getByRole('button',{name:'☰ МЕНЮ'}).click();await page.getByRole('button',{name:'Сдаться и выйти',exact:true}).click();await expect(page.getByRole('heading',{name:'Покинуть поле боя?'})).toBeVisible();await page.getByRole('button',{name:'Продолжить бой',exact:true}).click();await expect(page.locator('#dialog')).not.toBeVisible();
    await friend.setViewportSize({width:390,height:844});await friend.screenshot({path:'test-results/battle-mobile.png'});expect(await friend.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.getByRole('button',{name:'☰ МЕНЮ'}).click();await page.getByRole('button',{name:'Сдаться и выйти',exact:true}).click();await page.getByRole('button',{name:'Сдаться и выйти',exact:true}).click();await expect(page.locator('#browser')).toBeVisible();await expect(friend.getByRole('heading',{name:'Победа. Рубеж ваш.'})).toBeVisible();expect(errors).toEqual([]);
  }finally{for(const p of [page,friend])p.on('dialog',d=>d.accept());await a.close();await b.close();}
});
test('мобильный вход и список комнат без горизонтального переполнения',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await page.screenshot({path:'test-results/welcome-mobile.png'});await page.getByLabel('ПОЗЫВНОЙ',{exact:true}).fill('Mobile');await page.getByRole('button',{name:'Войти в штаб'}).click();await page.screenshot({path:'test-results/browser-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.getByRole('button',{name:'＋ Создать игру'})).toBeVisible();});
