import test from 'node:test';
import assert from 'node:assert/strict';
import {createMatch,command,step,TYPES} from '../server/simulation.mjs';
const players=[{id:'a',slot:0,name:'A'},{id:'b',slot:1,name:'B'}];
test('приказы не позволяют управлять чужими юнитами и передавать NaN',()=>{const s=createMatch(players);const enemy=s.units.find(u=>u.owner==='b');command(s,'a',{type:'move',ids:[enemy.id],x:0,z:0});assert.equal(enemy.order,null);assert.ok(command(s,'a',{type:'move',ids:[],x:NaN,z:0}));assert.ok(command(s,'a',{type:'produce',unit:'__proto__'}));});
test('производство списывает стоимость один раз и создаёт юнит после таймера',()=>{const s=createMatch(players);assert.equal(command(s,'a',{type:'produce',unit:'tank'}),null);assert.equal(s.players[0].credits,500);for(let i=0;i<81;i++)step(s,.1);assert.equal(s.units.filter(u=>u.owner==='a').length,7);assert.equal(s.players[0].queue.length,0);s.players[0].credits=0;assert.ok(command(s,'a',{type:'produce',unit:'tank'}));});
test('нефтяная вышка захватывается одним игроком и даёт дополнительный доход',()=>{const s=createMatch(players);s.units[0].x=0;s.units[0].z=0;for(let i=0;i<81;i++)step(s,.1);assert.equal(s.points[0].owner,'a');const c=s.players[0].credits;step(s,1);assert.equal(s.players[0].credits-c,16);});
test('оспариваемая вышка не захватывается',()=>{const s=createMatch(players);for(const id of ['a','b']){const u=s.units.find(u=>u.owner===id);u.x=id==='a'?-5:5;u.z=0;u.cooldown=100;}for(let i=0;i<90;i++)step(s,.1);assert.equal(s.points[0].owner,null);});
test('движение, стрельба, уничтожение штаба и остановка завершённого матча',()=>{const s=createMatch(players);const a=s.units[0];const x=a.x;command(s,'a',{type:'move',ids:[a.id],x:0,z:0});step(s,1);assert.notEqual(a.x,x);const b=s.bases[1];a.x=b.x-10;a.z=b.z;command(s,'a',{type:'attack',ids:[a.id],x:b.x,z:b.z,target:b.id});b.hp=TYPES.tank.damage;step(s,.1);assert.equal(s.ended,true);assert.equal(s.winner,'a');assert.equal(s.players[1].alive,false);const time=s.time;step(s,1);assert.equal(s.time,time);});
