import './style.css';
import {TYPES} from '../server/simulation.mjs';
import {Battlefield} from './renderer';
import {Connection} from './network';
import {Sound} from './sound';
import {$,COLORS,type Kind,type State,type Lobby,type RoomSummary} from './types';

const canvas=$<HTMLCanvasElement>('game'),dialog=$<HTMLDialogElement>('dialog');
const net=new Connection(),sound=new Sound();
let nickname='',myId='',room:Lobby|null=null,state:State|null=null,rooms:RoomSummary[]=[],selected=new Set<string>();
let mode:'move'|'attack'|'rally'|null=null,toastTime=0,endedShown=false,guarded=false,lastState=0,queueSignature='',rosterSignature='',roomSignature='';
let settings={volume:.25,quality:'normal',edgeScroll:false,protect:true};
try{nickname=localStorage.getItem('iron-nickname')||'';Object.assign(settings,JSON.parse(localStorage.getItem('iron-settings')||'{}'));}catch{}
const battle=new Battlefield(canvas,$<HTMLCanvasElement>('labels'));battle.onError=notify;battle.setQuality(settings.quality);sound.volume=settings.volume;
const groups=new Map<number,string[]>(),keys=new Set<string>();let groupRecall={id:0,time:0};
function notify(message:string){$('toast').textContent=message;$('toast').style.opacity='1';toastTime=5;$('lobby-error').textContent=message;}
function saveSettings(){try{localStorage.setItem('iron-settings',JSON.stringify(settings));}catch{}sound.volume=settings.volume;battle.setQuality(settings.quality);updateGuard();}
function unload(e:BeforeUnloadEvent){e.preventDefault();e.returnValue='';}
function updateGuard(){const active=!!(settings.protect&&state&&!state.ended&&state.players.find(p=>p.id===myId)?.alive);if(active===guarded)return;guarded=active;if(active)window.addEventListener('beforeunload',unload);else window.removeEventListener('beforeunload',unload);}
function setSelection(ids:Iterable<string>){selected=new Set(ids);battle.selected=selected;updateSelection();}
function resetControls(){keys.clear();pointer=null;$('box').style.display='none';}
function setMode(value:typeof mode){mode=value;$('command-mode').hidden=!mode;$('command-mode').textContent=mode==='rally'?'Укажите точку сбора · Esc отменить':mode==='attack'?'Укажите цель атаки · Shift добавить в очередь · Esc отменить':'Укажите позицию · Shift добавить в очередь · Esc отменить';canvas.style.cursor=mode?'crosshair':'default';for(const id of ['move','attack','rally'])$(id).classList.toggle('active',mode===id);}
function modal(title:string,content:string|HTMLElement,actions:{label:string;run:()=>void;primary?:boolean;danger?:boolean}[]=[]){resetControls();$('dialog-title').textContent=title;const body=$('dialog-body');body.replaceChildren();if(typeof content==='string')body.innerHTML=content;else body.append(content);const list=$('dialog-actions');list.replaceChildren();for(const action of actions){const b=document.createElement('button');b.textContent=action.label;if(action.primary)b.className='primary';if(action.danger)b.className='danger-button';b.onclick=action.run;list.append(b);}if(!dialog.open)dialog.showModal();}
function closeModal(){dialog.close();if(state)canvas.focus();}
$('dialog-close').onclick=closeModal;dialog.addEventListener('close',resetControls);
function help(){modal('Полевой справочник',`<table><tr><td>Выделить / добавить</td><td>ЛКМ / Shift + ЛКМ</td></tr><tr><td>Выделить группу / тип</td><td>Рамка / двойной ЛКМ</td></tr><tr><td>Движение / атака</td><td>ПКМ по земле / врагу</td></tr><tr><td>Режим атаки / движения</td><td>Q / M, затем ЛКМ</td></tr><tr><td>Очередь приказов</td><td>Shift + приказ</td></tr><tr><td>Стоп / все юниты</td><td>X / F</td></tr><tr><td>Записать / вызвать группу</td><td>Shift + 1–5 / 1–5</td></tr><tr><td>Камера / масштаб</td><td>WASD, средняя кнопка / колесо</td></tr><tr><td>К штабу / ремонт / точка сбора</td><td>H / B / R</td></tr><tr><td>Танк / БТР / САУ</td><td>Z / C / V</td></tr><tr><td>Меню / отмена режима</td><td>Esc</td></tr></table><p style="margin-top:20px">Вышка захватывается за 8 секунд без соперника рядом. Штаб даёт +4 ресурса/сек, каждая вышка — ещё +12. Повреждённая техника ремонтируется около штаба после 5 секунд без попаданий. Нажмите заказ в очереди, чтобы отменить его и вернуть ресурсы.</p><p style="margin-top:12px">Матч продолжается, пока открыто меню. При потере связи есть 60 секунд на возврат. Закрытие вкладки защищает стандартное предупреждение браузера; абсолютная блокировка его системных клавиш недоступна.</p>`,[{label:'Понятно',run:closeModal,primary:true}]);}
function settingsDialog(){modal('Настройки',`<div class="setting"><span>Громкость</span><input aria-label="Громкость" id="volume" type="range" min="0" max="1" step=".05" value="${settings.volume}"></div><div class="setting"><span>Качество графики</span><select id="quality" aria-label="Качество графики"><option value="low">Низкое</option><option value="normal">Среднее</option><option value="high">Высокое</option></select></div><label class="setting"><span>Камера у края экрана</span><input id="edge" type="checkbox" ${settings.edgeScroll?'checked':''}></label><label class="setting"><span>Предупреждать о закрытии матча</span><input id="protect" type="checkbox" ${settings.protect?'checked':''}></label><p style="margin-top:18px">Для игры без панелей браузера включите полный экран. Сочетания Ctrl и Alt не назначены на игровые команды.</p>`,[{label:'Полный экран',run:fullscreen},{label:'Готово',primary:true,run:closeModal}]);$<HTMLSelectElement>('quality').value=settings.quality;$<HTMLInputElement>('volume').oninput=()=>{settings.volume=Number($<HTMLInputElement>('volume').value);sound.volume=settings.volume;};$<HTMLInputElement>('volume').onchange=saveSettings;$<HTMLSelectElement>('quality').onchange=()=>{settings.quality=$<HTMLSelectElement>('quality').value;saveSettings();};$<HTMLInputElement>('edge').onchange=()=>{settings.edgeScroll=$<HTMLInputElement>('edge').checked;saveSettings();};$<HTMLInputElement>('protect').onchange=()=>{settings.protect=$<HTMLInputElement>('protect').checked;saveSettings();};}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('Полный экран недоступен здесь. Откройте игру в Chrome или Edge и нажмите F11.');}}
document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'⊡':'⛶';resetControls();});
function menu(){if(!state){settingsDialog();return;}modal(state.ended?'Матч завершён':'Командование',`<p>Матч идёт в реальном времени. Закройте меню, чтобы продолжить управление.</p><p style="margin-top:12px">Защита от закрытия: <strong>${guarded?'включена':'не требуется / выключена'}</strong>. Возврат после обрыва связи — до 60 секунд.</p>`,[{label:'Продолжить',run:closeModal,primary:true},{label:'Настройки',run:settingsDialog},{label:'Управление',run:help},...(state.ended&&room?.host===myId?[{label:'В лобби',run:()=>net.send({type:'rematch'})}]:[]),{label:state.ended?'Покинуть матч':'Сдаться и выйти',danger:true,run:askLeave}]);}
function askLeave(){if(!state||state.ended){exitRoom();return;}modal('Покинуть поле боя?',`<p>Явный выход засчитывается как поражение. Ваша техника и штаб покинут матч.</p><p class="danger" style="margin-top:12px">При случайном разрыве связи можно вернуться в течение 60 секунд.</p>`,[{label:'Продолжить бой',run:closeModal,primary:true},{label:'Сдаться и выйти',run:exitRoom,danger:true}]);}
function exitRoom(){net.send({type:'leave'});closeModal();}
function identity(edit=false){$<HTMLInputElement>('name').value=nickname;$('welcome').hidden=false;$('browser').hidden=true;$('room').hidden=true;$('edit-name').hidden=true;if(edit)$<HTMLInputElement>('name').focus();}
function browserPage(){state=null;battle.state=null;room=null;setMode(null);updateGuard();$('ui').hidden=true;$('lobby').hidden=false;$('welcome').hidden=true;$('browser').hidden=false;$('room').hidden=true;$('edit-name').hidden=false;$('nickname').textContent=nickname;$('lobby-error').textContent='';if(dialog.open)dialog.close();net.send({type:'list'});renderRooms();}
$<HTMLFormElement>('identity').onsubmit=e=>{e.preventDefault();const n=$<HTMLInputElement>('name').value.trim();if(!n){$<HTMLInputElement>('name').focus();return;}nickname=n.slice(0,20);try{localStorage.setItem('iron-nickname',nickname);}catch{}browserPage();};
$('edit-name').onclick=()=>{if(!room){identity(true);return;}const content=document.createElement('div'),label=document.createElement('label'),input=document.createElement('input');label.htmlFor='new-name';label.textContent='ПОЗЫВНОЙ';input.id='new-name';input.maxLength=20;input.value=nickname;content.append(label,input);modal('Изменить позывной',content,[{label:'Отмена',run:closeModal},{label:'Сохранить',primary:true,run:()=>{const n=input.value.trim();if(!n){input.focus();return;}nickname=n;try{localStorage.setItem('iron-nickname',nickname);}catch{}net.send({type:'rename',name:nickname});}}]);};$('lobby-help').onclick=help;$('lobby-settings').onclick=settingsDialog;$('help').onclick=help;$('menu').onclick=menu;$('fullscreen').onclick=fullscreen;
function createRoom(){if(!net.connected){notify('Нет связи с сервером');return;}const content=document.createElement('div');const p=document.createElement('p');p.textContent='Железные дюны · 2–4 игрока · каждый за себя';const label=document.createElement('label');label.htmlFor='room-name';label.textContent='НАЗВАНИЕ КОМНАТЫ';const input=document.createElement('input');input.id='room-name';input.maxLength=40;input.value='Комната '+nickname;content.append(p,label,input);modal('Создать игру',content,[{label:'Отмена',run:closeModal},{label:'Создать комнату',primary:true,run:()=>{net.send({type:'create',name:nickname,title:input.value});}}]);}
function join(code:string){if(!net.connected){notify('Нет связи с сервером');return;}net.send({type:'join',code,name:nickname});}
$('create').onclick=createRoom;$('join').onclick=()=>join($<HTMLInputElement>('code').value);$<HTMLInputElement>('code').onkeydown=e=>{if(e.key==='Enter')join($<HTMLInputElement>('code').value);};$('refresh').onclick=()=>{net.send({type:'list'});sound.play('click');};
function renderRooms(){const signature=JSON.stringify(rooms);if(signature===roomSignature&&$('room-list').childElementCount)return;roomSignature=signature;$('room-total').textContent=String(rooms.length);const list=$('room-list');list.replaceChildren();if(!rooms.length){const e=document.createElement('div');e.className='empty-rooms';e.innerHTML='<span>⌖</span><h3>Поле боя ждёт командиров</h3><p>Открытых комнат пока нет. Создайте игру — друзья увидят её в этом списке.</p>';list.append(e);return;}for(const r of rooms){const e=document.createElement('div');e.className='room-row';const info=document.createElement('div'),name=document.createElement('strong'),host=document.createElement('small'),count=document.createElement('span'),b=document.createElement('button');name.textContent=r.name;host.textContent=r.host+' · Железные дюны';info.append(name,host);count.className='slots';count.textContent=`${r.players} / 4`;b.textContent=r.status==='playing'?'В бою':r.status==='finished'?'Завершён':r.players>=4?'Заполнена':'Подключиться';b.disabled=r.status!=='waiting'||r.players>=4||!net.connected;b.onclick=()=>join(r.code);e.append(info,count,b);list.append(e);}}
function renderLobby(){if(!room)return;state=null;battle.state=null;updateGuard();$('lobby').hidden=false;$('ui').hidden=true;$('welcome').hidden=true;$('browser').hidden=true;$('room').hidden=false;$('edit-name').hidden=true;if(dialog.open)dialog.close();$('room-code').textContent=room.code;$('lobby-error').textContent='';const players=$('players');players.replaceChildren();for(let slot=0;slot<4;slot++){const p=room.players.find(p=>p.slot===slot),card=document.createElement('article');card.className='player-card'+(p?'':' empty');card.style.setProperty('--player-color',COLORS[slot]);const number=document.createElement('span');number.className='slot-number';number.textContent='0'+(slot+1);const type=document.createElement('small');type.textContent=p?.id===room.host?'СОЗДАТЕЛЬ КОМНАТЫ':p?'КОМАНДИР':'СВОБОДНАЯ ПОЗИЦИЯ';const name=document.createElement('h3');name.textContent=p?p.name+(p.id===myId?' · вы':''):'Ожидание игрока';const ready=document.createElement('div');ready.className='ready-state';ready.textContent=p?(p.ready?'● ГОТОВ К БОЮ':'○ ПОДГОТОВКА'):'Пригласите друга';card.append(number,type,name,ready);players.append(card);}
  $('edit-name').hidden=false;$('nickname').textContent=nickname;const ready=room.players.filter(p=>p.ready).length;$('ready-count').textContent=`${ready} / ${room.players.length} ГОТОВЫ`;$('ready').textContent=room.players.find(p=>p.id===myId)?.ready?'Отменить готовность':'Я готов';$<HTMLButtonElement>('start').disabled=room.host!==myId||room.players.length<2||ready!==room.players.length||!net.connected;$('start-hint').textContent=room.host!==myId?'Матч запускает создатель, когда все подтвердят готовность.':room.players.length<2?'Для старта нужен ещё хотя бы один игрок.':ready<room.players.length?'Ожидаем готовности всех командиров.':'Все готовы. Можно начинать.';}
$('ready').onclick=()=>net.send({type:'ready',ready:!room?.players.find(p=>p.id===myId)?.ready});$('start').onclick=()=>net.send({type:'start'});$('leave').onclick=()=>net.send({type:'leave'});
$('copy').onclick=async()=>{const url=new URL(location.href);url.searchParams.set('room',room!.code);try{await navigator.clipboard.writeText(url.toString());notify('Приглашение скопировано');}catch{modal('Приглашение',`<p>Скопируйте адрес и передайте друзьям:</p><input id="invite-value" aria-label="Ссылка приглашения" readonly>`,[{label:'Готово',run:closeModal,primary:true}]);$<HTMLInputElement>('invite-value').value=url.toString();$<HTMLInputElement>('invite-value').select();}};
const invited=new URL(location.href).searchParams.get('room');if(invited)$<HTMLInputElement>('code').value=invited.slice(0,6);
function beginMatch(s:State,resume=false){state=s;endedShown=false;mode=null;lastState=performance.now();queueSignature='';rosterSignature='';battle.begin(s,myId);setSelection(s.units.filter(u=>u.owner===myId).map(u=>u.id));$('lobby').hidden=true;$('ui').hidden=false;if(dialog.open)dialog.close();$('room-label').textContent=room?.code??'';resetControls();updateHud();updateGuard();canvas.focus();notify(resume?'Соединение восстановлено. Вы снова управляете отрядом.':'Матч начался. Вышки обеспечивают ресурсы, штаб ремонтирует технику.');if(s.ended)showResult();}
function showResult(){if(!state||endedShown)return;endedShown=true;const me=state.players.find(p=>p.id===myId)!,winner=state.players.find(p=>p.id===state!.winner);const content=document.createElement('div'),p=document.createElement('p');p.textContent=winner?`${winner.name} удержал поле боя.`:'Все штабы уничтожены.';content.append(p);const stats=document.createElement('div');stats.className='stats-grid';for(const [value,label] of [[me.kills,'УНИЧТОЖЕНО'],[me.produced,'ПОСТРОЕНО'],[$('clock').textContent,'ВРЕМЯ БОЯ']]){const block=document.createElement('div'),b=document.createElement('b'),small=document.createElement('small');b.textContent=String(value);small.textContent=String(label);block.append(b,small);stats.append(block);}content.append(stats);modal(state.winner===myId?'Победа. Рубеж ваш.':'Матч завершён',content,[{label:'Поле боя',run:closeModal},{label:room?.host===myId?'Вернуться в лобби':'К списку игр',primary:true,run:()=>net.send({type:room?.host===myId?'rematch':'leave'})}]);}
net.onMessage=m=>{if(m.type==='welcome')myId=m.id;if(m.type==='session')myId=m.id;if(m.type==='rooms'){rooms=m.rooms;renderRooms();}if(m.type==='lobby'){room=m;renderLobby();}if(m.type==='left'){net.forget();browserPage();battle.preview();}if(m.type==='resume_failed'){browserPage();battle.preview();notify(m.message);}if(m.type==='error'||m.type==='notice')notify(m.message);if(m.type==='host'&&room){room.host=m.host;if(state?.ended){endedShown=false;showResult();}}if(m.type==='start')beginMatch(m.state);if(m.type==='resumed'){room=m.room;beginMatch(m.state,true);}if(m.type==='state'){state=m.state;lastState=performance.now();battle.sync(state!);for(const e of state!.events){battle.event(e);if(e.type==='shot'||e.type==='explosion'){const pos=battle.screen(e.x,0,e.z);if(pos.x>0&&pos.x<innerWidth&&pos.y>0&&pos.y<innerHeight)sound.play(e.type);}else if(e.owner===myId&&e.type==='capture'){sound.play('capture');notify('Вышка захвачена · +12 ресурсов/сек');}else if(e.owner===myId&&e.type==='produced')sound.play('produced');}updateHud();updateGuard();if(state!.ended)showResult();}};
net.onStatus=(connected,message)=>{$('connection').textContent=(connected?'● ':'○ ')+message;for(const id of ['create','join','ready'])$<HTMLButtonElement>(id).disabled=!connected;roomSignature='';renderRooms();if(!connected){resetControls();notify(message);}$('connection-banner').hidden=connected||!state;$('connection-banner').textContent='Соединение прервано. Пробуем вернуться в матч — резерв 60 секунд.';};
function command(c:object){if(!net.connected||!state||state.ended||!state.players.find(p=>p.id===myId)?.alive){notify('Управление сейчас недоступно');return;}net.send({type:'command',command:c});}
function produce(type:Kind){command({type:'produce',unit:type});sound.play('click');}
function issue(x:number,z:number,target?:string,append=false){if(mode==='rally'){command({type:'rally',x,z});notify('Точка сбора установлена');setMode(null);return;}if(!selected.size){notify('Сначала выделите свою технику');return;}command({type:target||mode==='attack'?'attack':'move',ids:[...selected],x,z,target,append});sound.play('click');setMode(null);}
function stop(){command({type:'stop',ids:[...selected]});setMode(null);}function all(){setSelection(state?.units.filter(u=>u.owner===myId).map(u=>u.id)??[]);}function repair(){const b=state?.bases.find(b=>b.owner===myId);if(b)issue(b.x,b.z+(b.z>0?-12:12));}
$('move').onclick=()=>setMode(mode==='move'?null:'move');$('attack').onclick=()=>setMode(mode==='attack'?null:'attack');$('rally').onclick=()=>setMode(mode==='rally'?null:'rally');$('stop').onclick=stop;$('select-all').onclick=all;$('repair').onclick=repair;$('home').onclick=()=>battle.home();document.querySelectorAll<HTMLButtonElement>('[data-unit]').forEach(b=>b.onclick=()=>produce(b.dataset.unit as Kind));
function updateSelection(){if(!state)return;const units=state.units.filter(u=>selected.has(u.id));$('selected-count').textContent=String(units.length).padStart(2,'0');const same=units.length&&units.every(u=>u.type===units[0].type);$('selected-title').textContent=units.length===1?TYPES[units[0].type].name:units.length?`Боевая группа · ${units.length}`:'Выберите технику';$('selected-detail').textContent=units.length===1?`${Math.ceil(units[0].hp)} / ${units[0].maxHp} HP · ${units[0].repairing?'ремонт':TYPES[units[0].type].role}`:units.length?'ПКМ — приказ · Shift — очередь':'ЛКМ или рамка выделения';$<HTMLImageElement>('selected-portrait').src='/portraits/'+(same?units[0].type:'tank')+'.png';$('selected-hp').style.width=units.length?units.reduce((n,u)=>n+u.hp,0)/units.reduce((n,u)=>n+u.maxHp,0)*100+'%':'0%';const signature=units.map(u=>u.id).join(',');if(signature!==rosterSignature){rosterSignature=signature;const roster=$('unit-roster');roster.replaceChildren();for(const u of units){const b=document.createElement('button');b.title=TYPES[u.type].name+' · выбрать';b.setAttribute('aria-label',b.title);const image=document.createElement('img');image.src='/portraits/'+u.type+'.png';image.alt='';b.append(image);b.onclick=()=>setSelection([u.id]);roster.append(b);}}}
function updateHud(){if(!state)return;selected=new Set([...selected].filter(id=>state!.units.some(u=>u.id===id)));battle.selected=selected;const me=state.players.find(p=>p.id===myId);if(!me)return;const base=state.bases.find(b=>b.owner===myId)!;$('credits').textContent=Math.floor(me.credits).toLocaleString('ru');$('population').textContent=String(state.units.filter(u=>u.owner===myId).length);const n=state.points.filter(p=>p.owner===myId).length;$('income').textContent=`+${4+n*12} / сек`;$('capture').textContent=`${n} / 5 ВЫШЕК`;$('basehp').textContent=Math.max(0,Math.ceil(base.hp/base.maxHp*100))+'%';$('basebar').style.width=Math.max(0,base.hp/base.maxHp*100)+'%';$('clock').textContent=`${Math.floor(state.time/60).toString().padStart(2,'0')}:${Math.floor(state.time%60).toString().padStart(2,'0')}`;
  document.querySelectorAll<HTMLButtonElement>('[data-unit]').forEach(b=>{const t=TYPES[b.dataset.unit as Kind];b.disabled=!net.connected||!me.alive||state!.ended||me.credits<t.cost||me.queue.length>=5||state!.units.filter(u=>u.owner===myId).length+me.queue.length>=30;});
  const sig=me.queue.map(q=>q.id).join(',');if(sig!==queueSignature){queueSignature=sig;$('queue-items').replaceChildren();if(!me.queue.length)$('queue-items').textContent='Очередь пуста · закажите подкрепление';for(const q of me.queue){const b=document.createElement('button');b.id='queue-'+q.id;b.title='Отменить '+TYPES[q.type].name+' · вернуть '+TYPES[q.type].cost;b.setAttribute('aria-label',b.title);b.onclick=()=>command({type:'cancel',id:q.id});b.innerHTML='<i></i><span></span>';$('queue-items').append(b);}}
  for(const q of me.queue){const b=$('queue-'+q.id);if(b){b.querySelector('span')!.textContent=TYPES[q.type].name+' '+Math.ceil(q.left)+'с';(b.querySelector('i') as HTMLElement).style.transform=`scaleX(${1-q.left/TYPES[q.type].time})`;}}$('queue-label').textContent=me.queue.length?`${Math.ceil(me.queue[0].left)} С · ${me.queue.length} / 5`:'ГОТОВ';
  const opponents=$('opponents');opponents.replaceChildren();for(const p of state.players){const row=document.createElement('div');row.className='opponent';row.style.setProperty('--player-color',COLORS[p.slot]);const dot=document.createElement('i'),name=document.createElement('span'),status=document.createElement('small');name.textContent=p.name;const connection=state.connections.find(c=>c.id===p.id);status.textContent=!p.alive?'ВЫБЫЛ':connection&&!connection.connected?`СВЯЗЬ ${connection.reconnectSeconds}с`:'В БОЮ';row.append(dot,name,status);opponents.append(row);}updateSelection();renderGroups();}
function renderGroups(){for(let i=1;i<=5;i++){const ids=(groups.get(i)||[]).filter(id=>state?.units.some(u=>u.id===id));groups.set(i,ids);const b=$('group-'+i);b.querySelector('span')!.textContent=ids.length?String(ids.length):'—';b.title=`Группа ${i}: ${ids.length} · Shift+${i} записать`;}}
for(let i=1;i<=5;i++){const b=document.createElement('button');b.id='group-'+i;b.innerHTML=`${i}<span>—</span>`;b.onclick=e=>group(i,e.shiftKey);$('groups').append(b);}
function group(id:number,save=false){if(save){groups.set(id,[...selected]);notify(`Группа ${id}: ${selected.size} единиц`);renderGroups();return;}const ids=groups.get(id)||[];if(!ids.length){notify(`Shift + ${id} — сохранить выделение в группу`);return;}setSelection(ids);if(groupRecall.id===id&&performance.now()-groupRecall.time<450){const units=state!.units.filter(u=>selected.has(u.id));if(units.length)battle.focus.set(units.reduce((n,u)=>n+u.x,0)/units.length,0,units.reduce((n,u)=>n+u.z,0)/units.length);}groupRecall={id,time:performance.now()};}

let pointer:{x:number;y:number;lastX:number;lastY:number;button:number;shift:boolean}|null=null,mouse={x:0,y:0,inside:false};
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerenter',()=>mouse.inside=true);canvas.addEventListener('pointerleave',()=>mouse.inside=false);
canvas.addEventListener('pointerdown',e=>{sound.unlock();if(!state||dialog.open)return;canvas.focus();pointer={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,button:e.button,shift:e.shiftKey};canvas.setPointerCapture(e.pointerId);if(e.button===1)e.preventDefault();});
canvas.addEventListener('pointermove',e=>{mouse={x:e.clientX,y:e.clientY,inside:true};if(!pointer)return;if(pointer.button===1){const a=battle.worldAt(pointer.lastX,pointer.lastY),b=battle.worldAt(e.clientX,e.clientY);battle.focus.add(a.sub(b));pointer.lastX=e.clientX;pointer.lastY=e.clientY;return;}if(pointer.button===0&&!mode&&Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>6)Object.assign($('box').style,{display:'block',left:Math.min(pointer.x,e.clientX)+'px',top:Math.min(pointer.y,e.clientY)+'px',width:Math.abs(e.clientX-pointer.x)+'px',height:Math.abs(e.clientY-pointer.y)+'px'});});
canvas.addEventListener('pointerup',e=>{if(!pointer||!state)return;const p=pointer;pointer=null;$('box').style.display='none';if(p.button===1)return;const pos=battle.worldAt(e.clientX,e.clientY),hit=battle.hit(e.clientX,e.clientY);if(p.button===2||mode){issue(pos.x,pos.z,hit&&hit.owner!==myId?hit.id:undefined,e.shiftKey);return;}if(p.button!==0)return;const drag=Math.hypot(e.clientX-p.x,e.clientY-p.y)>6;if(!drag&&e.pointerType==='touch'&&selected.size&&!hit){issue(pos.x,pos.z);return;}const next=p.shift?new Set(selected):new Set<string>();if(drag){for(const u of state.units.filter(u=>u.owner===myId)){const s=battle.screen(u.x,1,u.z);if(s.x>=Math.min(p.x,e.clientX)&&s.x<=Math.max(p.x,e.clientX)&&s.y>=Math.min(p.y,e.clientY)&&s.y<=Math.max(p.y,e.clientY))next.add(u.id);}}else if(hit?.owner===myId&&'type' in hit){if(p.shift&&next.has(hit.id))next.delete(hit.id);else next.add(hit.id);}setSelection(next);});
canvas.addEventListener('pointercancel',resetControls);canvas.addEventListener('dblclick',e=>{const u=battle.hit(e.clientX,e.clientY,true);if(!u||!('type' in u)||!state)return;setSelection(state.units.filter(x=>x.owner===myId&&x.type===u.type).filter(x=>{const p=battle.screen(x.x,0,x.z);return p.x>0&&p.x<innerWidth&&p.y>0&&p.y<innerHeight;}).map(x=>x.id));});
canvas.addEventListener('wheel',e=>{if(!state||dialog.open)return;e.preventDefault();battle.zoom=Math.max(30,Math.min(125,battle.zoom+e.deltaY*.045));},{passive:false});
window.addEventListener('keydown',e=>{if((e.target as HTMLElement).matches('input,textarea,select')||dialog.open||!state)return;if(e.ctrlKey||e.metaKey||e.altKey)return;const code=e.code;if(code==='Escape'){e.preventDefault();if(mode)setMode(null);else menu();return;}const handled=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyF','KeyX','KeyQ','KeyM','KeyR','KeyB','KeyH','KeyZ','KeyC','KeyV','Digit1','Digit2','Digit3','Digit4','Digit5','Backspace','Space'];if(!handled.includes(code))return;e.preventDefault();keys.add(code);if(e.repeat)return;if(/^Digit[1-5]$/.test(code)){group(Number(code.slice(-1)),e.shiftKey);return;}const commands:Record<string,()=>void>={KeyF:all,KeyX:stop,KeyQ:()=>setMode(mode==='attack'?null:'attack'),KeyM:()=>setMode(mode==='move'?null:'move'),KeyR:()=>setMode(mode==='rally'?null:'rally'),KeyB:repair,KeyH:()=>battle.home(),KeyZ:()=>produce('tank'),KeyC:()=>produce('scout'),KeyV:()=>produce('artillery')};commands[code]?.();});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',resetControls);document.addEventListener('visibilitychange',()=>{if(document.hidden)resetControls();});document.addEventListener('pointerdown',()=>sound.unlock(),{once:true});
const minimap=$<HTMLCanvasElement>('minimap');minimap.oncontextmenu=e=>e.preventDefault();minimap.onpointerdown=e=>{if(!state||dialog.open)return;const r=minimap.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*124-62,z=(e.clientY-r.top)/r.height*124-62;if(e.button===2||mode)issue(x,z,undefined,e.shiftKey);else battle.focus.set(x,0,z);};
battle.onFrame=dt=>{if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').style.opacity='0';}if(!state)return;const speed=battle.zoom*.5*dt,a=battle.yaw*Math.PI/180;let dx=0,dz=0;if(!dialog.open){if(keys.has('KeyW')||keys.has('ArrowUp'))dz--;if(keys.has('KeyS')||keys.has('ArrowDown'))dz++;if(keys.has('KeyA')||keys.has('ArrowLeft'))dx--;if(keys.has('KeyD')||keys.has('ArrowRight'))dx++;if(settings.edgeScroll&&mouse.inside&&!pointer){if(mouse.x<8)dx--;if(mouse.x>innerWidth-8)dx++;if(mouse.y<8)dz--;if(mouse.y>innerHeight-8)dz++;}}
  battle.focus.x+=(dx*Math.cos(a)+dz*Math.sin(a))*speed;battle.focus.z+=(-dx*Math.sin(a)+dz*Math.cos(a))*speed;battle.drawMap(minimap);$('network').textContent=net.connected?`● ${net.latency} МС`:'○ НЕТ СВЯЗИ';const stalled=net.connected&&!state.ended&&performance.now()-lastState>3500;if(stalled){$('connection-banner').hidden=false;$('connection-banner').textContent='Ожидаем состояние от сервера…';}else if(net.connected)$('connection-banner').hidden=true;
};
if(nickname)browserPage();else identity();net.connect();void battle.load().then(()=>battle.drawMap($<HTMLCanvasElement>('map-preview'),true));
